author: Patryk Androsiuk

# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-dark
  social_links:
    - { platform: github,  user_url: "https://github.com/duchu-net/blog-pages" }
